name: Build apps

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        required: true
        default: bar
        description: Make a choice
        options:
          - foo
          - bar
          - baz

jobs:
  changed-apps:
    name: Derive changed apps
    runs-on: ubuntu-latest

    outputs:
      sha: "${{ steps.build-commit.outputs.SHA }}"

    steps:
      - name: Fetch custom branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Changes
        run: |
          echo
          echo "Release: ${{ inputs.release_type }}"
          echo "git rev-parse HEAD: $(git rev-parse HEAD)"
          echo "GITHUB_SHA:         $GITHUB_SHA"
          echo
          echo ${GITHUB_REF}
          git diff --name-only HEAD~1
          echo -------------------------------
          git diff --name-only origin/master HEAD~1

      - name: Build commit
        id: build-commit
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "git rev-parse $(git rev-parse HEAD)"
          echo ::set-output name=SHA::$(git rev-parse HEAD)

  checkout-commit:
    runs-on: ubuntu-latest
    needs: changed-apps
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.changed-apps.outputs.sha }}
      - run: |
          git rev-parse HEAD
