name: Tets caching a
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  show-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Show branch
        run: |
          echo Branch: ${GITHUB_REF#refs/heads/}
  job-a:
    runs-on: ubuntu-latest
    steps:
      - name: Cache dir a
        id: get-cache-a
        uses: actions/cache@v3
        env:
          cache-name: cache-a
        with:
          path: |
            ~/a
            ~/b
          key: x-cache-a
          restore-keys: |
            x-cache-

      - name: Get data
        run: |
          echo ls a
          [ -d ~/a ] && ls -lh ~/a || echo no dir a
          echo ls b
          [ -d ~/b ] && ls -lh ~/b || echo no dir b

      - name: Create content
        run: |
          mkdir -p ~/a
          echo 'a content' > ~/a/file.txt
          ls -lh ~/a
  job-b:
    runs-on: ubuntu-latest
    needs: job-a
    steps:
      - name: Cache dir b
        id: get-cache-b
        uses: actions/cache@v3
        env:
          cache-name: cache-b
        with:
          path: |
            ~/a
            ~/b
          key: x-cache-b
          restore-keys: |
            x-cache-

      - name: Get data
        run: |
          echo ls a
          [ -d ~/a ] && ls -lh ~/a || echo no dir a
          echo ls b
          [ -d ~/b ] && ls -lh ~/b || echo no dir b

      - name: Create content
        run: |
          mkdir -p ~/b
          echo 'b content' > ~/b/file.txt
          ls -lh ~/b
  job-both:
    needs:
      - job-a
      - job-b
    runs-on: ubuntu-latest
    steps:
      - name: Cache dir a
        id: get-cache-a
        uses: actions/cache@v3
        env:
          cache-name: cache-a
        with:
          path: |
            ~/a
            ~/b
          key: x-cache-a
          restore-keys: |
            x-cache-

      - name: Get data
        run: |
          echo ls a
          [ -d ~/a ] && ls -lh ~/a || echo no dir a
          echo ls b
          [ -d ~/b ] && ls -lh ~/b || echo no dir b
