name: Run tests for apps

on:
  workflow_call:
    inputs:
      apps:
        required: true
        type: string

jobs:
  test-app:
    name: Test app
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        app: ${{ fromJson(inputs.apps) }}
      fail-fast: false
      max-parallel: 3

    steps:
      - name: Run tests
        run: |
          echo "Testing ${{ matrix.app }}"
